#!/usr/bin/env python3

import queries
import os
import subprocess

import courses
import computing
import computingfaculty

DB_FILE = 'timetable.db'

print('deleting old database')
try:
    os.remove(DB_FILE)
except FileNotFoundError:
    pass

print('building schema')
subprocess.run(['sqlite3', DB_FILE], stdin=open('schema.sql'), check=True)

print('building term and holidays')
db = queries.DB(DB_FILE)
db.make_term('Spring 2026', '2026-01-12', '2026-04-28')
db.make_holiday('2026-01-19')
db.make_holiday('2026-02-16')
db.make_holiday('2026-03-09')
db.make_holiday('2026-03-10')
db.make_holiday('2026-03-11')
db.make_holiday('2026-03-12')
db.make_holiday('2026-03-13')

courses.build_courses(db)
computing.build_pre(db)
computingfaculty.build_faculty(db)
computing.build_post(db)

db.db.commit()


print('materializing views')
db.db.execute('ANALYZE')
db.db.execute('INSERT INTO conflict_pairs_materialized SELECT * FROM conflict_pairs')
db.db.execute('INSERT INTO anti_conflict_pairs_materialized SELECT * FROM anti_conflict_pairs')
db.db.execute('INSERT INTO time_slots_used_by_departments_materialized SELECT * FROM time_slots_used_by_departments')
db.db.execute('INSERT INTO time_slots_available_to_sections_materialized SELECT * FROM time_slots_available_to_sections')
db.db.commit()

db.db.execute('VACUUM')
db.db.execute('ANALYZE')

subprocess.run(['rm', '-r', '__pycache__'], check=True)
