[package]
name = "marmot"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[dependencies]
itertools = "0.14.0"
rand = "0.8.5"
sqlite = "0.36.1"
time = { version = "0.3.37", features = ["parsing"] }

