[package]
name = "marmot"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
itertools = "0.12.0"
rand = "0.8.5"
regex = "1.9.5"
time = { version = "0.3.28", features = ["parsing"]}
