[package]
name = "marmot"
version = "0.2.0"
edition = "2024"

[profile.dev]
opt-level = 3

[profile.release]
debug = true

[dependencies]
fastrand = "2.3.0"
itertools = "0.14.0"
kissat = "0.1.0"
sqlite = "0.36.1"
