[package]
name = "marmot"
version = "0.2.0"
edition = "2024"

[profile.dev]
opt-level = 3

[profile.release]
debug = true

[dependencies]
fastrand = "2.3.0"
rustsat = "0.6.4"
rustsat-cadical = "0.4.4"
rustsat-kissat = "0.3.4"
sqlite = "0.36.1"
