#!/usr/bin/env python3

import os
import subprocess

import courses
import computing
import computingfaculty
import queries

DB_FILE = 'timetable.db'

print('deleting old database')
try:
    os.remove(DB_FILE)
except FileNotFoundError:
    pass

print('building schema')
with open('schema.sql') as schema:
    subprocess.run(['sqlite3', DB_FILE], stdin=schema, check=True)

print('building term and holidays')
db = queries.DB(DB_FILE)
db.make_term('Spring 2027', '2027-01-11', '2027-05-04')
db.make_holiday('2027-01-18')
db.make_holiday('2027-02-15')
db.make_holiday('2027-03-08')
db.make_holiday('2027-03-09')
db.make_holiday('2027-03-10')
db.make_holiday('2027-03-11')
db.make_holiday('2027-03-12')

courses.build_courses(db)
computing.build_pre(db)
computingfaculty.build_faculty(db)
computing.build_post(db)

db.db.commit()

db.db.execute('VACUUM')
db.db.execute('ANALYZE')

subprocess.run(['rm', '-r', '__pycache__'], check=True)
