#!/usr/bin/env python3

import importlib.util
import os
from pathlib import Path
import subprocess

import common
import courses
import computing
import computingfaculty
import mathematics
import mathfaculty
import queries

DB_FILE = 'timetable.db'

print('deleting old database')
try:
    os.remove(DB_FILE)
except FileNotFoundError:
    pass

print('building schema')
subprocess.run(['sqlite3', DB_FILE], stdin=open('schema.sql'), check=True)

print('building term and holidays')
db = queries.DB(DB_FILE)
db.make_term('Fall 2026', '2026-08-19', '2026-12-10')
db.make_holiday('2026-09-07')
db.make_holiday('2026-10-15')
db.make_holiday('2026-10-16')
db.make_holiday('2026-11-23')
db.make_holiday('2026-11-24')
db.make_holiday('2026-11-25')
db.make_holiday('2026-11-26')
db.make_holiday('2026-11-27')

courses.build_courses(db)
common.build_pre(db)
computing.build_pre(db)
mathematics.build_pre(db)
computingfaculty.build_faculty(db)
mathfaculty.build_faculty(db)
computing.build_post(db)
mathematics.build_post(db)

db.db.commit()


print('materializing views')
db.db.execute('ANALYZE')
db.db.execute('INSERT INTO conflict_pairs_materialized SELECT * FROM conflict_pairs')
db.db.execute('INSERT INTO anti_conflict_pairs_materialized SELECT * FROM anti_conflict_pairs')
db.db.execute('INSERT INTO time_slots_used_by_departments_materialized SELECT * FROM time_slots_used_by_departments')
db.db.execute('INSERT INTO time_slots_available_to_sections_materialized SELECT * FROM time_slots_available_to_sections')
db.db.commit()

db.db.execute('VACUUM')
db.db.execute('ANALYZE')

subprocess.run(['rm', '-r', '__pycache__'], check=True)
